# a2enconf
# Autogenerated from man page /usr/share/man/man8/a2enconf.8.gz
# using Deroffing man parser
complete -c a2enconf -s q -l quiet --description 'Don\'t show informative messages.'
complete -c a2enconf -s m -l maintmode --description 'Enables the maintainer mode, that is the progra… [See Man Page]'
complete -c a2enconf -s p -l purge --description 'When disabling a module, purge all traces of th… [See Man Page]'

