# catfish
# Autogenerated from man page /usr/share/man/man1/catfish.1.gz
# using Deroffing man parser
complete -c catfish -l version --description 'show program\'s version number and exit.'
complete -c catfish -s h -l help --description 'show this help message and exit.'
complete -c catfish -s v -l verbose --description 'Show debug messages (-vv debugs catfish_lib also).'
complete -c catfish -l large-icons --description 'Use large icons.'
complete -c catfish -l thumbnails --description 'Use thumbnails.'
complete -c catfish -l iso-time --description 'Display time in ISO format.'
complete -c catfish -l path --description 'Search in folder PATH.'
complete -c catfish -l fileman --description 'Use FILEMAN as filemanager.'
complete -c catfish -l wrapper --description 'Use WRAPPER to open files.'
complete -c catfish -l exact --description 'Perform exact match.'
complete -c catfish -l hidden --description 'Include hidden files.'
complete -c catfish -l fulltext --description 'Perform fulltext search.'

