# diodon
# Autogenerated from man page /usr/share/man/man1/diodon.1.gz
# using Deroffing man parser
complete -c diodon -s h -l help --description 'Show help options.'
complete -c diodon -s v -l version --description 'Print version information CHECKSUM Specific cli… [See Man Page]'

