# docker-inspect
# Autogenerated from man page /usr/share/man/man1/docker-inspect.1.gz
# using Deroffing man parser
complete -c docker-inspect -l help --description '  Print usage statement.'
complete -c docker-inspect -s f -l format --description '   Format the output using the given go template.'

