# docker-build
# Autogenerated from man page /usr/share/man/man1/docker-build.1.gz
# using Deroffing man parser
complete -c docker-build -s f -l file --description '   Path to the Dockerfile to use.'
complete -c docker-build -l force-rm --description '   Always remove intermediate containers, even … [See Man Page]'
complete -c docker-build -l no-cache --description '   Do not use cache when building the image.'
complete -c docker-build -l help --description '  Print usage statement.'
complete -c docker-build -l pull --description '   Always attempt to pull a newer version of the image.'
complete -c docker-build -s q -l quiet --description '   Suppress the verbose output generated by the containers.'
complete -c docker-build -l rm --description '   Remove intermediate containers after a successful build.'
complete -c docker-build -s t -l tag --description '   Repository name (and optionally a tag) to be… [See Man Page]'

