# gnome-mines
# Autogenerated from man page /usr/share/man/man6/gnome-mines.6.gz
# using Deroffing man parser
complete -c gnome-mines -s x -l width --description 'Width of grid.'
complete -c gnome-mines -s y -l height --description 'Height of grid.'
complete -c gnome-mines -s n -l mines --description 'Number of mines.'
complete -c gnome-mines -s f -l size --description 'Size of the board (0-2 = small-large, 3=custom).'
complete -c gnome-mines -s a -l a --description 'X location of window.'
complete -c gnome-mines -s b -l b --description 'Y location of window.'

