# gvfs-rename
# Autogenerated from man page /usr/share/man/man1/gvfs-rename.1.gz
# using Deroffing man parser
complete -c gvfs-rename -s h -l help --description 'Prints a short help text and exits.'

