# light-locker-command
# Autogenerated from man page /usr/share/man/man1/light-locker-command.1.gz
# using Deroffing man parser
complete -c light-locker-command -s l -l lock --description 'Tells the running display manager to lock the s… [See Man Page]'
complete -c light-locker-command -s V -l version --description 'Version of this application SEE ALSO light-locker (1).'

