# light-locker
# Autogenerated from man page /usr/share/man/man1/light-locker.1.gz
# using Deroffing man parser
complete -c light-locker -l debug --description 'Enable debugging code.'
complete -c light-locker -l lock-after-screensaver --description 'Lock the screen S seconds after the screensaver started.'
complete -c light-locker -l late-locking --description 'Lock the screen on screensaver deactivation.'
complete -c light-locker -l lock-on-suspend --description 'Lock the screen on suspend/resume.'

