# menulibre
# Autogenerated from man page /usr/share/man/man1/menulibre.1.gz
# using Deroffing man parser
complete -c menulibre -l version --description 'show program\'s version number and exit.'
complete -c menulibre -s h -l help --description 'show this help message and exit.'
complete -c menulibre -s v -l verbose --description 'Show debug messages SEE ALSO The full documenta… [See Man Page]'

