# mugshot
# Autogenerated from man page /usr/share/man/man1/mugshot.1.gz
# using Deroffing man parser
complete -c mugshot -l version --description 'show program\'s version number and exit.'
complete -c mugshot -s h -l help --description 'show this help message and exit.'
complete -c mugshot -s v -l verbose --description 'Show debug messages (-vv debugs mugshot_lib als… [See Man Page]'

