# nethogs
# Autogenerated from man page /usr/share/man/man8/nethogs.8.gz
# using Deroffing man parser
complete -c nethogs -s d --description 'delay for refresh rate.'
complete -c nethogs -s h --description 'display available commands usage.'
complete -c nethogs -s p --description 'sniff in promiscious mode (not recommended).'
complete -c nethogs -s t --description 'tracemode.'
complete -c nethogs -s V --description 'prints Version info.'

