# NetworkManager
# Autogenerated from man page /usr/share/man/man8/NetworkManager.8.gz
# using Deroffing man parser
complete -c NetworkManager -l version --description 'Print the NetworkManager software version and exit.'
complete -c NetworkManager -l help --description 'Print NetworkManager\'s available options and exit.'
complete -c NetworkManager -l no-daemon --description 'Do not daemonize.'
complete -c NetworkManager -l pid-file --description 'Specify location of a PID file.'
complete -c NetworkManager -l state-file --description 'Specify file for storing state of the NetworkMa… [See Man Page]'
complete -c NetworkManager -l config --description 'Specify configuration file to set up various se… [See Man Page]'
complete -c NetworkManager -l plugins --description 'List plugins used to manage system-wide connection settings.'
complete -c NetworkManager -l log-level --description 'Sets how much information NetworkManager sends … [See Man Page]'
complete -c NetworkManager -l log-domains --description 'Sets which operations are logged to the log des… [See Man Page]'
complete -c NetworkManager -l connectivity-uri --description 'Sets the URI of a web page that will be used fo… [See Man Page]'
complete -c NetworkManager -l connectivity-interval --description 'Sets the interval (in seconds) in which connect… [See Man Page]'
complete -c NetworkManager -l connectivity-response --description 'If set, it controls what body content NetworkMa… [See Man Page]'

