# odt2sxw
# Autogenerated from man page /usr/share/man/man1/odt2sxw.1.gz
# using Deroffing man parser
complete -c odt2sxw -s c -l connection --description 'UNO connection string to be used by the client … [See Man Page]'
complete -c odt2sxw -s d -l doctype --description 'Specify the LibreOffice document type of the backend format.'
complete -c odt2sxw -s e -l export --description 'Set specific export filter options (related to … [See Man Page]'
complete -c odt2sxw -s f -l format --description 'Specify the output format for the document.'
complete -c odt2sxw -s i -l import --description 'Set specific import filters options (related to… [See Man Page]'
complete -c odt2sxw -s l -l listener --description 'Start unoconv as listener for unoconv clients to connect to.'
complete -c odt2sxw -s n -l no-launch --description 'By default if no listener is running, unoconv w… [See Man Page]'
complete -c odt2sxw -s o -l output --description 'If the argument is a directory, put the convert… [See Man Page]'
complete -c odt2sxw -l pipe --description 'Use a pipe as an alternative connection mechani… [See Man Page]'
complete -c odt2sxw -s p -l port --description 'Port to listen on (as listener) or to connect to (as client).'
complete -c odt2sxw -s s -l server --description 'Server (address) to listen on (as listener) or … [See Man Page]'
complete -c odt2sxw -l show --description 'List the possible output formats to be used with -f.'
complete -c odt2sxw -l stdout --description 'Print converted output file to stdout.'
complete -c odt2sxw -s t -l template --description 'Specify the template to use for importing styles from.'
complete -c odt2sxw -s T -l timeout --description 'When unoconv starts its own listener, try to co… [See Man Page]'
complete -c odt2sxw -s v -l verbose --description 'Be more and more and more verbose.'
complete -c odt2sxw -o 'f.' --description '.'

