# plank
# Autogenerated from man page /usr/share/man/man1/plank.1.gz
# using Deroffing man parser
complete -c plank -l help --description 'Show help options.'
complete -c plank -s n -l name --description 'The name of for dock.  Defaults to "dock1".'
complete -c plank -s d -l debug --description 'Enable debug level logging.'
complete -c plank -s v -l verbose --description 'Enable verbose level logging.'
complete -c plank -s V -l version --description 'Show the version.'
complete -c plank -l preferences --description 'Show preferences dialog of the just started or … [See Man Page]'

