# pyvenv-3
# Autogenerated from man page /usr/share/man/man1/pyvenv-3.4.1.gz
# using Deroffing man parser
complete -c pyvenv-3 -s h -l help --description 'show this help message and exit.'
complete -c pyvenv-3 -l system-site-packages --description 'Give the virtual environment access to the syst… [See Man Page]'
complete -c pyvenv-3 -l symlinks --description 'Attempt to symlink rather than copy.'
complete -c pyvenv-3 -l clear --description 'Delete the environment directory if it already exists.'
complete -c pyvenv-3 -l upgrade --description 'Upgrade the environment directory to use this v… [See Man Page]'

