# redshift-gtk
# Autogenerated from man page /usr/share/man/man1/redshift-gtk.1.gz
# using Deroffing man parser
complete -c redshift-gtk -s h --description 'Display this help message.'
complete -c redshift-gtk -s v --description 'Verbose output.'
complete -c redshift-gtk -s V --description 'Show program version.'
complete -c redshift-gtk -s b --description 'Screen brightness to apply (max is 1. 0).'
complete -c redshift-gtk -s c --description 'Load settings from specified configuration file.'
complete -c redshift-gtk -s g --description 'Additional gamma correction to apply.'
complete -c redshift-gtk -s l --description 'Your current location.'
complete -c redshift-gtk -s m --description 'Method to use to set color temperature (Type `l… [See Man Page]'
complete -c redshift-gtk -s o --description 'One shot mode (do not continuously adjust color temperature).'
complete -c redshift-gtk -s O --description 'One shot manual mode (set color temperature).'
complete -c redshift-gtk -s x --description 'Reset mode (remove adjustment from screen).'
complete -c redshift-gtk -s r --description 'Disable temperature transitions.'
complete -c redshift-gtk -s t --description 'Color temperature to set at daytime/night.'

