# systemd-udevd-kernel
# Autogenerated from man page /usr/share/man/man8/systemd-udevd-kernel.socket.8.gz
# using Deroffing man parser
complete -c systemd-udevd-kernel -l daemon --description 'Detach and run in the background.'
complete -c systemd-udevd-kernel -l debug --description 'Print debug messages to stderr.'
complete -c systemd-udevd-kernel -l children-max --description 'Limit the number of events executed in parallel.'
complete -c systemd-udevd-kernel -l exec-delay --description 'Delay the execution of RUN instruction by the g… [See Man Page]'
complete -c systemd-udevd-kernel -l resolve-names --description 'Specify when systemd-udevd should resolve names… [See Man Page]'
complete -c systemd-udevd-kernel -l version --description 'Print version number.'
complete -c systemd-udevd-kernel -l help --description 'Print help text.'

