# tasksel
# Autogenerated from man page /usr/share/man/man8/tasksel.8.gz
# using Type1
complete -c tasksel -s t -l test --description 'test mode; don\'t actually install or remove packeges.'
complete -c tasksel -l new-install --description 'automatically select some tasks without even di… [See Man Page]'
complete -c tasksel -l list-tasks --description 'list on stdout the tasks that would be displaye… [See Man Page]'
complete -c tasksel -l task-packages --description 'lists on stdout the packages that are available… [See Man Page]'
complete -c tasksel -l task-desc --description 'outputs the extended description of the given task.'
complete -c tasksel -l debconf-apt-from --description 'Start the debconf-apt-progress bar here.'
complete -c tasksel -l debconf-apt-to --description 'End the debconf-apt-progress bar here.'

