# thunar-volman-settings
# Autogenerated from man page /usr/share/man/man1/thunar-volman-settings.1.gz
# using Deroffing man parser
complete -c thunar-volman-settings -s h -l help --description 'Show help options.'
complete -c thunar-volman-settings -l help-all --description 'Show all help options.'
complete -c thunar-volman-settings -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c thunar-volman-settings -l class --description 'Program class as used by the window manager.'
complete -c thunar-volman-settings -l name --description 'Program name as used by the window manager.'
complete -c thunar-volman-settings -l screen --description 'X screen to use.'
complete -c thunar-volman-settings -l sync --description 'Make X calls synchronous.'
complete -c thunar-volman-settings -l gtk-module --description 'Load additional GTK+ modules.'
complete -c thunar-volman-settings -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c thunar-volman-settings -l display --description 'X display to use AUTHOR Written by Benedikt Meurer <benny@xfce.'

