# x-session-manager
# Autogenerated from man page /usr/share/man/man1/x-session-manager.1.gz
# using Deroffing man parser
complete -c x-session-manager -l disable-tcp --description 'Disable binding to TCP ports in the ICE layer.'
complete -c x-session-manager -l help --description 'Print a help screen and exit.'
complete -c x-session-manager -l version --description 'Output version information and exit.'

