# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
# using Deroffing man parser
complete -c x-window-manager -s h -l help --description 'Show help options.'
complete -c x-window-manager -l help-all --description 'Show all help options.'
complete -c x-window-manager -l help-gtk --description 'Show GTK+ Options.'
complete -c x-window-manager -l help-sm-client --description 'Show session management options . SS "Application Options:".'
complete -c x-window-manager -l daemon --description 'Fork to the background.'
complete -c x-window-manager -l compositor --description 'Set the compositor mode.'
complete -c x-window-manager -l replace --description 'Replace the existing window manager.'
complete -c x-window-manager -s V -l version --description 'Print version information and exit.'
complete -c x-window-manager -l display --description 'X display to use Released under the terms of th… [See Man Page]'

