# x86_64-linux-gnu-gcc-ranlib-4
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gcc-ranlib-4.8.1.gz
# using Deroffing man parser
complete -c x86_64-linux-gnu-gcc-ranlib-4 -l plugin --description '.'

