# xfce4-settings-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-manager.1.gz
# using Deroffing man parser
complete -c xfce4-settings-manager -s h -l help --description 'Show help options.'
complete -c xfce4-settings-manager -l help-all --description 'Show all help options.'
complete -c xfce4-settings-manager -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c xfce4-settings-manager -l class --description 'Program class as used by the window manager.'
complete -c xfce4-settings-manager -l name --description 'Program name as used by the window manager.'
complete -c xfce4-settings-manager -l screen --description 'X screen to use.'
complete -c xfce4-settings-manager -l sync --description 'Make X calls synchronous.'
complete -c xfce4-settings-manager -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfce4-settings-manager -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c xfce4-settings-manager -s V -l version --description 'Version information.'
complete -c xfce4-settings-manager -s d -l dialog --description 'Settings dialog to show.'
complete -c xfce4-settings-manager -l display --description 'X display to use COPYRIGHT Copyright © 2008-201… [See Man Page]'

