# xfce4-settings-editor
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-editor.1.gz
# using Deroffing man parser
complete -c xfce4-settings-editor -s h -l help --description 'Show help options.'
complete -c xfce4-settings-editor -l help-all --description 'Show all help options.'
complete -c xfce4-settings-editor -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c xfce4-settings-editor -l class --description 'Program class as used by the window manager.'
complete -c xfce4-settings-editor -l name --description 'Program name as used by the window manager.'
complete -c xfce4-settings-editor -l screen --description 'X screen to use.'
complete -c xfce4-settings-editor -l sync --description 'Make X calls synchronous.'
complete -c xfce4-settings-editor -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfce4-settings-editor -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c xfce4-settings-editor -s V -l version --description 'Version information.'
complete -c xfce4-settings-editor -l display --description 'X display to use COPYRIGHT Copyright © 2008-201… [See Man Page]'

