# xfce4-mime-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-mime-settings.1.gz
# using Deroffing man parser
complete -c xfce4-mime-settings -s h -l help --description 'Show help options.'
complete -c xfce4-mime-settings -l help-all --description 'Show all help options.'
complete -c xfce4-mime-settings -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c xfce4-mime-settings -l class --description 'Program class as used by the window manager.'
complete -c xfce4-mime-settings -l name --description 'Program name as used by the window manager.'
complete -c xfce4-mime-settings -l screen --description 'X screen to use.'
complete -c xfce4-mime-settings -l sync --description 'Make X calls synchronous.'
complete -c xfce4-mime-settings -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfce4-mime-settings -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c xfce4-mime-settings -s v -l version --description 'Version information.'
complete -c xfce4-mime-settings -l display --description 'X display to use COPYRIGHT Copyright © 2008-201… [See Man Page]'

