# xfce4-volumed
# Autogenerated from man page /usr/share/man/man1/xfce4-volumed.1.gz
# using Deroffing man parser
complete -c xfce4-volumed -s h -l help --description 'Show help options.'
complete -c xfce4-volumed -l help-all --description 'Show all help options.'
complete -c xfce4-volumed -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-volumed -s v -l version --description 'Version information.'
complete -c xfce4-volumed -l no-daemon --description 'Do not fork to the background.'
complete -c xfce4-volumed -l display --description 'X display to use.'

