# xfce4-about
# Autogenerated from man page /usr/share/man/man1/xfce4-about.1.gz
# using Deroffing man parser
complete -c xfce4-about -s h -l help --description 'Show help options.'
complete -c xfce4-about -l help-all --description 'Show all help options.'
complete -c xfce4-about -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-about -s V -l version --description 'Version information.'
complete -c xfce4-about -l display --description 'X display to use COPYRIGHT Copyright © 2008-201… [See Man Page]'

