# xfce4-appfinder
# Autogenerated from man page /usr/share/man/man1/xfce4-appfinder.1.gz
# using Deroffing man parser
complete -c xfce4-appfinder -s h -l help --description 'Show help options.'
complete -c xfce4-appfinder -l help-all --description 'Show all help options.'
complete -c xfce4-appfinder -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-appfinder -s c -l collapsed --description 'Start in collapsed mode.'
complete -c xfce4-appfinder -s V -l version --description 'Print version information and exit.'
complete -c xfce4-appfinder -s r -l replace --description 'Replace the existing service.'
complete -c xfce4-appfinder -s q -l quit --description 'Quit all instances.'
complete -c xfce4-appfinder -l disable-server --description 'Do not try to use or become a D-Bus service.'
complete -c xfce4-appfinder -l display --description 'X display to use REPORTING BUGS Please report b… [See Man Page]'

