# xfdesktop-settings
# Autogenerated from man page /usr/share/man/man1/xfdesktop-settings.1.gz
# using Deroffing man parser
complete -c xfdesktop-settings -s h -l help --description 'Show help options.'
complete -c xfdesktop-settings -l help-all --description 'Show all help options.'
complete -c xfdesktop-settings -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c xfdesktop-settings -l class --description 'Program class as used by the window manager.'
complete -c xfdesktop-settings -l name --description 'Program name as used by the window manager.'
complete -c xfdesktop-settings -l screen --description 'X screen to use.'
complete -c xfdesktop-settings -l sync --description 'Make X calls synchronous.'
complete -c xfdesktop-settings -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfdesktop-settings -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c xfdesktop-settings -s s -l socket-id --description 'Settings manager socket.'
complete -c xfdesktop-settings -s V -l version --description 'Version information.'
complete -c xfdesktop-settings -l display --description 'X display to use COPYRIGHT Copyright © 2004-200… [See Man Page]'

