# xfsettingsd
# Autogenerated from man page /usr/share/man/man1/xfsettingsd.1.gz
# using Deroffing man parser
complete -c xfsettingsd -s h -l help --description 'Show help options.'
complete -c xfsettingsd -l help-all --description 'Show all help options.'
complete -c xfsettingsd -l help-gtk --description 'Show GTK+ Options.'
complete -c xfsettingsd -l help-sm-client --description 'Show session management options . PP GTK+ Options.'
complete -c xfsettingsd -l class --description 'Program class as used by the window manager.'
complete -c xfsettingsd -l name --description 'Program name as used by the window manager.'
complete -c xfsettingsd -l screen --description 'X screen to use.'
complete -c xfsettingsd -l sync --description 'Make X calls synchronous.'
complete -c xfsettingsd -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfsettingsd -l g-fatal-warnings --description 'Make all warnings fatal . PP Session management options.'
complete -c xfsettingsd -l sm-client-id --description 'Session management client ID.'
complete -c xfsettingsd -l sm-client-disable --description 'Disable session management . SS "Application Options:".'
complete -c xfsettingsd -s V -l version --description 'Version information.'
complete -c xfsettingsd -l no-daemon --description 'Do not fork to the background.'
complete -c xfsettingsd -l replace --description 'Replace running xsettings daemon (if any).'
complete -c xfsettingsd -l display --description 'X display to use COPYRIGHT Copyright © 2008-201… [See Man Page]'

